apiVersion: v1
kind: ConfigMap
metadata:
  name: nugusauce-api-config
data:
  REDIS_HOST: "shared-redis-master.cache.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_URL: "https://nugusauce.jaehyuns.com"
  PROD_MAIL_FROM_NAME: "NuguSauce"
  DISCORD_WEBHOOK_URL: ""
  CLOUDINARY_CLOUD_NAME: "dyzg8xb4n"
