apiVersion: v1
kind: Secret
metadata:
  name: nugusauce-api-secret
type: Opaque
stringData:
  PROD_DB_URL: "jdbc:postgresql://shared-postgresql.database.svc.cluster.local:5432/nugusauce"
  PROD_DB_USERNAME: "postgres"
  PROD_DB_PASSWORD: "replace-me"
  PROD_JWT_SECRET: "replace-me"
  MAIL_USERNAME: "noreply@example.com"
  MAIL_PASSWORD: "replace-me"
  KAKAO_NATIVE_APP_KEY: "replace-me"
  CLOUDINARY_API_KEY: "replace-me"
  CLOUDINARY_API_SECRET: "replace-me"
