apiVersion: ENC[AES256_GCM,data:V1k=,iv:NZohlrYa4WDhjdBgvUf3vT5GJPS3T8FgnPIOAe2FLfs=,tag:fsDl4iqXN0CnAbOul1joKg==,type:str]
kind: ENC[AES256_GCM,data:LJ4ejFJiCkDo,iv:x4yTkRoAXH+sAfsUaqoFWDktYAaFb2aaFIjXGbwbELI=,tag:f5emV1dW9O5BMQ8xJDcEWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ohpbTLYLLTAxg6JieETKRon1kvo=,iv:Tg6r59nYjIPUKOm+n8fV9ih0ONVzKnygv6gk/hSKK2E=,tag:+fcY34NipQYHprQd7Lfg/A==,type:str]
data:
    REDIS_HOST: ENC[AES256_GCM,data:pOUZWbOsRbN6fNpclbgC87us4wNxBrc99BbJxzfV3phnpa7jG6Ko8us1JQ==,iv:2C8xPp63vJHsYHJY7hqAxxsAPjyslXGQbF849fL3yAo=,tag:Xj9Sf8MaXQJaKN68BUZ+gQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:N3CZ6Q==,iv:ATa8xWjpDJY5GfshvU6KIB82woeTMJNs3z+/l8oJEQk=,tag:39p1l4WTDhDAauz2ohW3gA==,type:str]
    REDIS_DB: ENC[AES256_GCM,data:kA==,iv:CNvep7NUk6HiYCGvEmjXULF8FbtXjgwfFSzApDJ8gno=,tag:Vm1GmJGRLZaUwXQm5BK00Q==,type:str]
    APP_URL: ENC[AES256_GCM,data:uVV+lt3W9X3BnpFQ3AvJ6+XfVmGdshvNC7hUsxQK,iv:UdgN2Rl70OKyg96HQWnEDymxFfkt5ptc1f8Ec5Zu8Cg=,tag:+JeNrbOiT3D6dlM5lGWDlA==,type:str]
    PROD_MAIL_FROM_NAME: ENC[AES256_GCM,data:/6izwPpDbgl5,iv:6OTI79HRT7QiN5gstHXKrc78NcVnf9dguB0BqYFIKb0=,tag:PP2+qPUdrQahkAXj/6j5zA==,type:str]
    DISCORD_WEBHOOK_URL: ""
    CLOUDINARY_CLOUD_NAME: ENC[AES256_GCM,data:885Jr8tzG0eX,iv:PypamhNve1VvH4qqnJ5KfwJT7MxxioQaBcwOod57b1w=,tag:+nx1uwiROiV4CxB1jDuOfA==,type:str]
    APPLE_CLIENT_ID: ENC[AES256_GCM,data:7ZVe8sGzcOntSaPQapxzf9g=,iv:aKe7A4ToB3l6pRK2Ks/O1AcOk33eb1OOq6IEWhrHtiQ=,tag:D3cBYJMIQ4jkLgUbZzcRuQ==,type:str]
sops:
    age:
        - recipient: age1su7wslu0uwtef3uy6uzvvc4ke5lhk4un6tddaexqh2w8y5lvzu8qf29545
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzLzlOSnhrL3lNd2YyS3Q4
            SWhiL3QrM0FTYUpIYUNlYllBaGVrT2g4TEJnCks1MGREY3FDWVRnUm41RFQ0djA3
            VGJVU2hxbXlsY0tPL1Y4ZGs4V3dLb0UKLS0tIEVJQXdGWDNGZnQrYlYwUW1sYWo5
            NmRTUUN6S1pHQmRWSlF1S3VHdk1FUkkKvZ47yCOlkrQvEyU2eiOZTkGX4O3GlNad
            6Ta+5LsH+3uzkYVrv/J6SJ6LNVlGGoJhracqpE4KH5ULtFu2uiJrQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T07:00:19Z"
    mac: ENC[AES256_GCM,data:KRusq3zbRUxgZh21DB8ZuACzqUPYVXFJBnVC2lPYwSU+9gInPgddsNumTKMgXwH/AEiLOcElaPaxKC0T8xMi1hzdxdpVhVzD0CGTBjL+qU0PV2whHFfaOMbFWj424Vt+Thk8SAAtzbeAVldG7jpdgGFJboFari9cwbXh7R/5GtE=,iv:pG9Vl4AhKMx0WxCUjUORD4CpKY0JBL6um66t/7OLujQ=,tag:0U1UXSyqHOM1o+o36mY8pQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
