apiVersion: ENC[AES256_GCM,data:jb8=,iv:GnEY54yH19h3LVBdsDRQPQjjPNaUhStWZv6PG5aO/mg=,tag:anZR0POPqLnIkFk/niKcKg==,type:str]
kind: ENC[AES256_GCM,data:jerSY88Z,iv:V0UZO5/thEenbDbus6VwkVfP3OS9BGMmu5iLhwf+3A4=,tag:QoX3zr+wlDFU6f9LbKBxUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qxVDji5Dn260MDaz7lfE2jzX07Q=,iv:2Sc9I9SP2uyQzjNohNfU/sRALaMUJEIwufTRIeqf3mg=,tag:uiboDKPL/ioM3C/jC5ab8w==,type:str]
type: ENC[AES256_GCM,data:SfwbeFov,iv:VTGymml28tY51c1zTbAybf+G8WCA3cQW/QJTWq6wj9k=,tag:pmNFYlRaenXgB+Yda5NsTQ==,type:str]
stringData:
    PROD_DB_URL: ENC[AES256_GCM,data:+6Iy432ggkudAIBWIeHTBmekc477z2Y46fIauslpiNd/VwUEFn76wkhR9/0g4b6R/U0kCLVYp6VPbmZOe4ec5qqtBimdgIf8ckYVMMM=,iv:NXP0OG2Z+Emr/KIJP9uU2XNrri73/Suclz8dzqm2/Hs=,tag:y6yNoL4GRSllO7gSCP5xKg==,type:str]
    PROD_DB_USERNAME: ENC[AES256_GCM,data:V1KT7WUxRXXu,iv:ppQSxaFktlM5j/t1K35EDo0prFm0MaumUEW75raHlxc=,tag:GmbqzF5+oep9luAYHu8xow==,type:str]
    PROD_DB_PASSWORD: ENC[AES256_GCM,data:rvz91MTVOq/6gOCa7Ofj99/Klckv0o/vMtmNH8bZTIjk+SlOIcNjY+v+tdeQzy7zs+JcF+VBAzyfXp+1cqjVDA==,iv:VJ1P6KWXK9YBznk4B5oB2hWkQKXojoZX6gQD69N0jA8=,tag:vt9CPqnfXrD60TZ11xJ8PA==,type:str]
    PROD_JWT_SECRET: ENC[AES256_GCM,data:RfgwGVdeQ9bRLfP7bNz9NWdIQBH3MMHvc8tQNT1jHRI+pQ62uMOiNZZg88xX42JZwQhyPFPOUvHulz06Ma79x+2Jqlt19lXOUL8w2bgxGJwnBIzgup1JEA==,iv:506GAJ5ALky5uAAJoD27wzl0G8IPHUUDCZZa7LEqffA=,tag:4jCFCHoIfNAZ+NB1OMQNVA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:thPgz7Bheey2AxqxHZ2QM1SlXiK68rc=,iv:FGLOmjp8dkB1wbGBdFp+iW1cfAVM2sMv3Y3HK6ueNEA=,tag:QFunKZdlwNS0nFd5GY3+Zg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:GWBQWlvmRSv3Pxb2Em7nsUBGXA==,iv:XQb/XmSDhFpxNekA/RVSZPjjTMH2pYaMbNq0Srt5Htk=,tag:bRntlYWV7kJ3fk7O2POwoQ==,type:str]
    KAKAO_NATIVE_APP_KEY: ENC[AES256_GCM,data:KClx7XeXS6sLNqg/kbESL4ZnEiOOtuHkJTc1/zl7PxM=,iv:0uclzqtKYXtXybA93Uog0VsG7E5VDfOOshRXtwYy0hw=,tag:8uZCpbLvG8xeoHG6BX0D7g==,type:str]
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:Y2QkjHTOEpLHWCCpGgbn,iv:dKyzbbsDnFti9AYilGLSrs6S6n5bEBKS+zPpXdOCdRE=,tag:JxRVGXQRFqB+oDZF3RIsCw==,type:int]
    CLOUDINARY_API_SECRET: ENC[AES256_GCM,data:sEFNlVMsUo3/jAZEZc0V9vC2iD6dM9fzYdaq,iv:Q5dahGFWudmA07lW57dp2O8hr0iSubN3YJHpdXPHye4=,tag:WM/jlhw/VD2huN36R2fiow==,type:str]
sops:
    age:
        - recipient: age1su7wslu0uwtef3uy6uzvvc4ke5lhk4un6tddaexqh2w8y5lvzu8qf29545
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaHpKaU13d1g4ZERITWRK
            alFKRlJUZk5tVHU4eVpFMmNMb1BBYVNUd2s0CjUyRFpNNU13dHdqU0x3dy80OXYr
            QnN5RnJXN2tXcjdCejZPbFpFOHZ3cGsKLS0tIEVXMXhkb0c1ZFdlQW5idTl5L1lo
            cXlkeTF5YmZLUFpobVRmcCs1S1ZjOEkK52Dh/+2jGVQgoFaKlzAvvA4GZ/mFwWBN
            EehxQ+nUWPpwTk9RjckpdkjAb1dyT3mjmYg9M08p9EYDClcIgVNavw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:19:57Z"
    mac: ENC[AES256_GCM,data:6mkqJY2gw3O0SbXEXVALsE3/EHJUx4eyL+/V+VaQ6HlQIfW5Nva6tPH+8ir3dGJ38N5hyUmsnn/NSJre8bsM8Ao8zar5v1TCEaGbRzMDpx1ZE5UOQsDt4SuNTTOqOAYBtFk1MgEBlJmydWYwR/5KjGYVz8eWngY8kwYzBLboFfY=,iv:x9VDuMIgtLq78RcRP/rBiiWzTB+dlDkvsqjsthlh51g=,tag:DeHsuObbi5UB9Sz9S5lqNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
