apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nugusauce-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wingwogus/NuguSauce.git
    targetRevision: main
    path: ops/helm/nugusauce-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nugusauce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
